#! /usr/bin/env python
# Copyright (c) 2013, NVIDIA CORPORATION.  All Rights Reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

import os
import sys
from optparse import OptionParser

from pm342 import pm342
from pm292 import pm292

if __name__ == "__main__":
    pm342_targets = pm342.supported_targets
    pm292_targets = pm292.supported_targets

    parser = OptionParser()
    parser.set_defaults()
    parser.add_option("--target", "-t", action="store", type="string",
                      dest="target", help="Target board [%s]" % " | ".join(pm342_targets + pm292_targets))
    parser.add_option("--serial", "-s", action="store", type="string",
                      dest="serial", help="Serial of debug board. Defaults to the value of PMXXX_SERIAL environment variable.")
    parser.add_option("--variant", "-v", action="store", type="string",
                      dest="variant", help="Target board variant [A00 | A01 | A02 | A03 | ...]")
    (options, args) = parser.parse_args()

    if options.serial is None and "PMXXX_SERIAL" in os.environ:
        options.serial = os.environ["PMXXX_SERIAL"]
        print >>sys.stderr, "NOTE: Using --serial=%s from environment." % options.serial

    if options.target in pm342_targets:
        pmxxx = pm342(serial = options.serial, target = options.target, variant = options.variant)
    elif options.target in pm292_targets:
        pmxxx = pm292(serial = options.serial, target = options.target, variant = options.variant)
    else:
        print ("'%s' is not a supported target board\nUse one of following: [%s]" %
               (options.target, " | ".join(pm342_targets + pm292_targets)))
        exit(1)

    if len(args) != 1:
        print >>sys.stderr, "Must give a board control command: reset | recovery | usb_{on,off} | recovery_{up,down} | onkey | power_{on,off} | status"
        sys.exit(1)

    if args[0] == "reset":
        pmxxx.target_reset()
    elif args[0] == "recovery":
        pmxxx.target_recovery_mode()
    elif args[0] == "usb_on":
        pmxxx.enable_USB()
    elif args[0] == "usb_off":
        pmxxx.disable_USB()
    elif args[0] == "recovery_down":
        pmxxx.hold_button("FORCE_RECOVERY")
    elif args[0] == "recovery_up":
        pmxxx.release_button("FORCE_RECOVERY")
    elif args[0] == "onkey":
        pmxxx.push_button("ONKEY")
    elif args[0] == "power_on":
        pmxxx.target_power_on()
    elif args[0] == "power_off":
        pmxxx.target_power_off()
    elif args[0] == "status":
        print("VDD_CORE is %s" % ("on" if pmxxx.is_VDD_CORE_on() else "off"))
        print("VDD_CPU is %s" % ("on" if pmxxx.is_VDD_CPU_on() else "off"))
        for gpio in sorted([x for x in pmxxx.get_IO_names() if "GPIO" in x]):
            print(gpio + " is %d" % pmxxx.get_IO(gpio))
    else:
        print >>sys.stderr, "Must give a board control command: reset | recovery | usb_{on,off} | recovery_{up,down} | onkey | power_{on,off} | status"
