#!/bin/bash

#cd $P4ROOT

#source /usr/local/bin/nvidia-buildenvp4-setup.sh

#p4 login

p4 sync -f //sw/tools/ARM/Linux/RVDS_2_2/...
p4 sync -f //sw/tools/linux/binutils-2.13.90.0.18-9/...
p4 sync -f //sw/tools/linux/gcc-3.2.2-5/...
p4 sync -f //sw/tools/linux/glibc-devel-2.3.2-11.9-i686/...
p4 sync -f //sw/tools/linux/kernel/redhat-9.0/...
p4 sync -f //sw/tools/linux/python/251/...
p4 sync -f //sw/mobile/tools/linux/jhstaff/...
p4 sync -f //sw/mobile/tools/linux/misc/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/cgc/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/cmake-2.6.2/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/cmake-2.8.6/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/doxygen-1.5.8/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/doxygen-1.8.1/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/patchutils-0.2.31-3/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/perl-5.10.0/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/prevent-linux-4.3.0/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/python-2.5.1-26/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/rpm-4.3.2-5/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/targets/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/texlive-2011/...
p4 sync -f //sw/tools/unix/hosts/Linux-x86/unix-build/...
p4 sync -f //sw/tools/unix/targets/Linux-x86/...
p4 sync -f //sw/tools/unix/targets/Linux-x86_64/...
p4 sync -f //sw/tools/unix/targets/common/...
p4 sync -f //sw/mobile/tools/linux/yocto/gcc-4.8.1-glibc-2.18-hard/...
p4 sync -f //sw/mobile/tools/linux/yocto/gcc-4.8.1-glibc-2.18-hard-rev1/...
p4 sync -f //sw/mobile/tools/linux/yocto/gcc-4.8.1-glibc-2.18-hard-rev2/...
p4 sync -f //sw/misc/linux/...
p4 sync -f //sw/mobile/tools/linux/crosstool-ng/arm-cortex_a9-linux-gnueabi/gcc-4.5.3-glibc-2.11.3-softfp/...
p4 sync -f //sw/mobile/tools/linux/crosstool-ng/arm-cortex_a9-linux-gnueabi/gcc-4.5.3-glibc-2.11.3-hard/...
p4 sync -f //sw/mobile/tools/linux/crosstool-ng/arm-cortex_a9-linux-gnueabi/gcc-4.5.3-glibc-2.15-hard/...
p4 sync -f //sw/devrel/SDK/inc/GL/...
p4 sync -f //sw/tools/embedded/vendor/nvidia/tegra2-4.4.1-nv-rev3/arm-none-eabi/...
p4 sync -f //sw/mobile/tools/linux/xorg/arm-none-linux-gnueabi/...
p4 sync -f //sw/tools/unix/targets/Linux-ARMv7-gnueabihf/...
p4 sync -f //sw/embedded/benchmarks/...
p4 sync -f //sw/embedded/external-prebuilt/...
p4 sync -f //sw/mobile/linux/distro/mobile_ldk/target_filesystem/...
p4 sync -f //sw/embedded/tools/toolchains/linaro-4_7-2013q1/...
p4 sync -f //sw/mobile/tools/linux/linaro/aarch64-none-elf-4.9-2014.07/...
p4 sync -f //sw/embedded/external/yocto/packaging/yocto-tegra-initramfs-rootfs.img
p4 sync -f //sw/tools/ddk/X/...
p4 sync -f //sw/tools/linux/gtk+-2.2.1/...
p4 sync -f //sw/tools/unix/targets/Linux-aarch64/...
p4 sync -f //sw/tools/unix/targets/Linux-ARMv7-gnueabi/...
p4 sync -f //sw/tools/embedded/vendor/nvidia/linaro-4.5.1/...
p4 sync -f //sw/apps/gpu/drivers/unix/binaries/Linux_ARMv7_gnueabihf/...
p4 sync -f //sw/embedded/tools/src/toolchains/yocto/...
p4 sync -f //sw/embedded/tools/src/toolchains/crosstool-ng-1.16.0/...
p4 sync -f //sw/embedded/external/gstreamer/...
p4 sync -f //sw/embedded/external/chm_reader/...
p4 sync -f //sw/embedded/external/jpeg/libjpeg/...
p4 sync -f //sw/embedded/external/mtd-utils/...
p4 sync -f //sw/embedded/data/vbios/...
p4 sync -f //sw/embedded/release/misc/...
p4 sync -f //sw/embedded/apt-repos/tegra-15.04-arm64/...
p4 sync -f //sw/embedded/apt-repos/tegra-14.04-armhf/...
p4 sync -f //sw/embedded/apt-repos/tegra-13.10-armhf/...
p4 sync -f //sw/devtools/metools/public/MapComposer/Main/Demos/...
p4 sync -f //sw/mobile/tools/linux/linaro/aarch64-linux-gnu_4.7-2013.02-01/...
p4 sync -f //sw/mobile/tools/linux/linaro/aarch64-unknown-linux-gnu_4.9-2014.05-01/...
p4 sync -f //sw/tools/android/ndk/...
p4 sync -f //sw/mobile/tools/linux/android/nvmake/...
p4 sync -f //sw/mobile/apps/devrel/...
p4 sync -f //sw/tools/embedded/qnx/qnx670/...

sudo chown root $P4ROOT/sw/misc/linux/unix-build
sudo chmod u+s $P4ROOT/sw/misc/linux/unix-build

#cd -

