#!/bin/bash
echo $P4ROOT
par=$1
## command_list
common_list=(
//sw/embedded/tools/toolchains/linaro-4_7-2013q1/...
//sw/mobile/tools/linux/linaro/aarch64-none-elf-4.9-2014.07/...
//sw/tools/unix/hosts/Linux-x86/doxygen-1.5.8/...
//sw/tools/unix/hosts/Linux-x86/perl-5.10.0/...
//sw/tools/unix/hosts/Linux-x86/python-2.5.1-26/...
//sw/tools/unix/hosts/Linux-x86/python-2.7.11/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-x86/binutils-2.18/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-x86/configs/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-x86/gcc-4.1.1as2/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-x86_64/binutils-2.22/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-x86_64/configs/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-x86_64/gcc-4.1.1as2/...
//sw/tools/unix/hosts/Linux-x86/unix-build/...
//sw/tools/unix/targets/common/...
//sw/tools/unix/targets/Linux-x86/glibc-2.2.2-10/...
//sw/tools/unix/targets/Linux-x86/gcc-devel-2.1.3/...
//sw/tools/unix/targets/Linux-x86/linux-libc-headers-2.6.12.0/...
//sw/tools/unix/targets/Linux-x86_64/glibc-2.2.5-0/...
)

##Linux list
linux_list=(
//sw/embedded/external-prebuilt/dso-stubs/...
//sw/embedded/external-prebuilt/Linux-aarch64/...
//sw/embedded/external-prebuilt/wayland*/...
//sw/embedded/external-prebuilt/xserver/...
//sw/embedded/tools/toolchain-from-cogent/arm-cortex_a15-linux-gnueabi/gcc-4.8.1-glibc-2.18-softfp/...
//sw/mobile/linux/distro/mobile_ldk/target_filesystem/sample_fs_xenial_desktop_arm64.tbz2
//sw/mobile/tools/linux/linaro/aarch64-unknown-linux-gnu_4.9-2014.05-01/...
//sw/mobile/tools/linux/xorg/...
//sw/tools/unix/targets/Linux-aarch64/...
)

##QNX list
qnx_list=(
//sw/tools/embedded/qnx/qnx700-alpha/...
//sw/tools/embedded/qnx/qnx700-eval/...
//sw/tools/embedded/qnx/qnx700-r30/...
)

##integrity
integrity_list=(
//sw/tools/unix/hosts/Linux-x86/targets/Linux-aarch64/binutils-2.24/...
)

tool_list=(
//sw/misc/linux/unix-build
//sw/tools/unix/hosts/Linux-x86/...
//sw/tools/unix/hosts/Linux-x86/targets/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-x86/...
//sw/tools/unix/hosts/Linux-x86/targets/Linux-ARMv7-gnueabihf/...
//sw/tools/unix/targets/common/...
//sw/tools/unix/targets/Linux-x86/...
//sw/tools/unix/targets/Linux-ARMv7-gnueabihf/...
)

echo "Start sync p4 !!" > ${P4ROOT}/p4sync.log
echo "Start sync p4 common !!" >> $P4ROOT/p4sync.log
for ((i=0; i<${#common_list[@]}; i++)); do
    p4 sync $par ${common_list[$i]} >> $P4ROOT/p4sync.log 2>&1
done

echo "Start sync p4 linux !!" >> $P4ROOT/p4sync.log
for ((i=0; i<${#linux_list[@]}; i++)); do 
    p4 sync $par ${linux_list[$i]} >> $P4ROOT/p4sync.log 2>&1
done

echo "Start sync p4 qnx !!" >> $P4ROOT/p4sync.log
for ((i=0; i<${#qnx_list[@]}; i++)); do
    p4 sync $par ${qnx_list[$i]} >> $P4ROOT/p4sync.log 2>&1
done

echo "Start sync p4 integrity !!" >> $P4ROOT/p4sync.log
for ((i=0; i<${#integrity_list[@]}; i++)); do
    p4 sync $par ${integrity_list[$i]} >> $P4ROOT/p4sync.log 2>&1
done

echo "Start sync p4 tool !!" >> $P4ROOT/p4sync.log
for ((i=0; i<${#tool_list[@]}; i++)); do
    p4 sync $par ${tool_list[$i]} >> $P4ROOT/p4sync.log 2>&1
done

