#!/bin/bash
p4 sync -f //sw/mobile/tools/linux/...
p4 sync -f //sw/misc/linux/unix-build/...
p4 sync -f //sw/tools/embedded/vendor/nvidia/...
p4 sync -f //sw/misc/linux/... //ncho_android_minimal/sw/misc/linux/...
p4 sync -f //sw/devrel/SDK/inc/GL/... //ncho_android_minimal/sw/devrel/SDK/inc/GL/...
p4 sync -f //sw/tools/embedded/vendor/nvidia/tegra2-4.4.1-nv-rev3/arm-none-eabi/... 
p4 sync -f //sw/tools/unix/hosts/Linux-x86/targets/Linux-ARMv7-gnueabihf/... 
p4 sync -f //sw/mobile/tools/linux/xorg/arm-none-linux-gnueabi/... 
p4 sync -f //sw/tools/unix/targets/Linux-ARMv7-gnueabihf/... 
p4 sync -f //sw/embedded/benchmarks/... 
p4 sync -f //sw/embedded/external-prebuilt/... 
p4 sync -f //sw/mobile/linux/distro/mobile_ldk/target_filesystem/... 
p4 sync -f //sw/embedded/tools/toolchains/linaro-4_7-2013q1/... 
p4 sync -f //sw/mobile/tools/linux/xorg/...
p4 sync -f //sw/tools/ddk/X/...
p4 sync -f //sw/tools/linux/gtk+-2.2.1/...
p4 sync -f //sw/tools/unix/targets/common/libdrm/...
p4 sync -f //sw/tools/unix/targets/common/xorg-server/...
p4 sync -f //sw/mobile/tools/linux/yocto/gcc-4.8.1-glibc-2.18-hard-rev2/...
