#!/bin/bash
export P4ROOT="/home/ncho/Projects/upload/p4"
p4 sync //sw/embedded/docs/projects/active/android/OAA/...
p4 sync //sw/embedded/docs/projects/active/vibrante_3.0/...
p4 sync //sw/embedded/docs/projects/active/vibrante_4.0/...
p4 sync //sw/embedded/docs/projects/active/jetson/...
p4 sync //sw/tools/unix/hosts/Linux-x86/targets/...
